# Generated by Django 2.2.1 on 2019-05-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
