# Generated by Django 2.2.1 on 2019-05-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testForm', '0002_formdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDat',
        ),
    ]
